#!/bin/bash

python /gae/render_app_yaml.py --input ./template.yaml --output ./app.yaml \
	--APP_ORIGIN ${APP_ORIGIN} \
	--MANAGER_ORIGIN ${MANAGER_ORIGIN} \
	--ASSET_BUCKET_NAME ${ASSET_BUCKET_NAME} \
	--DATASTORE_PROJECT_ID ${DATASTORE_PROJECT_ID} \
	--GIN_MODE debug \
	--GOOGLE_APPLICATION_CREDENTIALS ${GOOGLE_APPLICATION_CREDENTIALS} \
	--LMM_API_TOKEN_KEY ${LMM_API_TOKEN_KEY}
