#!/bin/sh

python script/generate_app_yaml.py \
    --DATASTORE_PROJECT_ID=${DATASTORE_PROJECT_ID} \
    --GIN_MODE=${GIN_MODE} \
    --GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS} \
    --LMM_API_TOKEN_KEY=${LMM_API_TOKEN_KEY}
